# Generated by Django 4.1.5 on 2023-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=100)),
                ('full_detail', models.TextField()),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='createSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('adress', models.CharField(max_length=500)),
                ('phonenum', models.CharField(max_length=15)),
            ],
        ),
    ]
