# Generated by Django 4.1.6 on 2023-02-12 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_createproduct_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproduct',
            name='seller',
            field=models.ForeignKey(default=5,on_delete=django.db.models.deletion.CASCADE, to='products.createsellers'),
        ),
        migrations.AlterField(
            model_name='createproduct',
            name='producttype',
            field=models.CharField(choices=[('oyoq kiyim', 'oyoq kiyim'), ('shim', 'shim'), ("ko'ylak", "ko'ylak"), ('futbolka', 'futbolka'), ('kamar', 'kamar'), ('kurtka', 'kurtka'), ('ichki kyim', 'ichki kyim'), ('batnik', 'batnik'), ('sportifka', 'sportifka'), ('shapka', 'shapka'), ('svetr', ' svetr')], default='nomalum', max_length=200),
        ),
    ]
