# Generated by Django 4.1.6 on 2023-02-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_createproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='seller',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='products.createsellers'),
        ),
    ]
