# Generated by Django 4.1.6 on 2023-03-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_createproduct_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='producttype',
            field=models.CharField(choices=[('Bosh kiyimlar', 'Bosh kiyimlar'), ("ko'ylaklar", "ko'ylaklar"), ("Etiklar va qo'nji kalta etiklar", "Etiklar va qo'nji kalta etiklar"), ('Shimlar va jinsilar', 'Shimlar va jinsilar'), ('Tufli va mokasinlar', 'Tufli va mokasinlar'), ('Futbolkalar va maykalar', 'Futbolkalar va maykalar'), ('Sport kiyimlari', 'Sport kiyimlari'), ('Jemperlar va sviterlar', 'Jemperlar va sviterlar'), ('Ustki kiyimlar', 'Ustki kiyimlar'), ("Kostyumlar va to'plamlar", "Kostyumlar va to'plamlar"), ('Pidjaklar va jiletlari', 'Pidjaklar va jiletlari'), ('Krossovkalar va kedalar', ' Krossovkalar va kedalar')], default='nomalum', max_length=200),
        ),
    ]
