# Generated by Django 4.1.6 on 2023-03-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_createproduct_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproduct',
            name='offer',
            field=models.CharField(choices=[('hech qaysi', 'none'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%')], default='none', max_length=12),
        ),
    ]
