# Generated by Django 4.1.6 on 2023-03-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_createproduct_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createproduct',
            name='offer',
            field=models.CharField(choices=[('none', 'hech qaysi'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%')], default='none', max_length=12),
        ),
    ]
