# Generated by Django 4.1.6 on 2023-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_createproduct_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='createproduct',
            name='offered',
            field=models.CharField(blank=True, default=None, max_length=200,null=True),
        ),
    ]
