# Generated by Django 4.1.6 on 2023-05-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_createproduct_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createproduct',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='createproduct',
            name='offered',
        ),
    ]
